### ISSUE TITLE
Bluetooth Connection

### ISSUE THREAD

**Issue by TaWeiYeh** [kerryeven/AndroidArtemisBleUartClient#2]
Hi Kerry, 

Thank you for the App resource. I couldn't figure out how to connect to Amdtps on Artemis Nano without this repository. 
I can successfully upload Viper2_7 to Arduino and KeRobotNrf to my Android phone. However, the Bluetooth connection isn't stable or constant. It required me multiple tries on my phone to connect Artemis Nano. Does it happen to you as well?

Thanks

**Comment by kerryeven** [comment]
Ocassionally that has happened when I was using Bluetooth audio on same phone.  Found that re-booting phone cleared it up.  Works pretty much all of the time now on Moto G6 Android Pie or Nvidia Shield 8.1 Android tablet. 
It will not connect until you see the LED_BUILTIN flash repeatedly for a couple of seconds which signals the end of the bootup.  
And, I have never had an unstable or non-constant connection, which is why I love this board for my robot.  
Remember that there is a WatchDogTimer that will reboot the chip if it loses comm to the Android for 2 sec's or so.  So, does it lose connection due to nano rebooting (WatchDog expiring), or does the phone lose the connection causing the nano to reboot (also WDT but phone causes it). You could hook to pc and watch serial ouput without phone. Should see ...@@@Timer2 ISR @@@.... about every 2 sec's with a count.  I usually get around 100+ counts before any trouble when connected to phone or just running by self.  
Good luck...glad it helped in a little way.  If you find a problem, please let me know how you fixed it.
Kerry    On Thursday, May 14, 2020, 07:49:18 PM EDT, TaWeiYeh <notifications@github.com> wrote:  
 
 


Hi Kerry,

Thank you for the App resource. I couldn't figure out how to connect to Amdtps on Artemis Nano without this repository.
I can successfully upload Viper2_7 to Arduino and KeRobotNrf to my Android phone. However, the Bluetooth connection isn't stable or constant. It required me multiple tries on my phone to connect Artemis Nano. Does it happen to you as well?

Thanks

**Comment by TaWeiYeh** [comment]
Hi Kerry, 

Thank you for the detailed reply. It is actually my phone's problem. The connection works after I reboot my Samsung S10+. I was connected to my audio before connecting to Artemis Nano. The connection is stable now. And keep counting more to 450+. 
Thank you.
