### ISSUE TITLE
Transfer UartService to the second Activity

### ISSUE THREAD

**Issue by TaWeiYeh** [kerryeven/AndroidArtemisBleUartClient#5]
Hi Kerry, 

I have created a new activity that creates a joystick. However, to send the message to Artemis Nano, I would have to pass the UartService to the new activity and send the joystick coordinate. How do I transfer the existed UartService to the new activity?

Thank you.

**Comment by kerryeven** [comment]
look at MainActivity function private void service_init()at line 887 in my version of this program to see how MainActivity calls UartService.
Need to create new instance of class at top of MainActivity like:private UartService mService = null;that's at line 54 on mine.
then call the mService which is the instance of UartService with:
mService.writeRXCharacteristic(value);

Kerry    On Thursday, June 4, 2020, 05:34:37 AM EDT, TaWeiYeh <notifications@github.com> wrote:  
 
 


Hi Kerry,

I have created a new activity that creates a joystick. However, to send the message to Artemis Nano, I would have to pass the UartService to the new activity and send the joystick coordinate. How do I transfer the existed UartService to the new activity?

Thank you.

**Comment by TaWeiYeh** [comment]
Thank you, Kerry. I have also referred to this page for how to bound the service [https://developer.android.com/guide/components/bound-services](url). 

This is my Github that adds Joystick option. Thank you for your help. 
[https://github.com/TaWeiYeh/ArtemisBleApp](url).

**Comment by kerryeven** [comment]
Love the joystick, nice work


On Jun 5, 2020 at 4:03 AM, TaWeiYeh <notifications@github.com> wrote:

Thank you, Kerry. I have also referred to this page for how to bound the
service https://developer.android.com/guide/components/bound-services <url>.

This is my Github that adds Joystick option. Thank you for your help.
https://github.com/TaWeiYeh/ArtemisBleApp <url>.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/kerryeven/AndroidArtemisBleUartClient/issues/5#issuecomment-639324348>,
or unsubscribe
